export const courses = [
  {
    id: "1",
    name: "Professional Development Course for Primary School Teachers ",
    topics: [
      "values",
      "citizenship",
      "ways of acquiring citizenship",
      "fundamental human rights",
      "traffic regulations",
      "inter-communal relationship",
      "nationality",
      "cultism",
    ],
    students: "22,200",
    courseLength: "18 units",
  },
  {
    id: "2",
    name: "Professional Development Course for Secondary School Teachers ",
    topics: [
      "normalization",
      "database modelling",
      "data integrity",
      "transactions",
      "rules of transactions",
      "skeletons and bones",
      "taxonomy of life",
      "flowers",
      "fruits",
      "photosynthesis",
    ],
    students: "19,200",
    courseLength: "10 units",
  },
];
