"use client";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Container from "@/components/common/ui/Container";
import { usePathname, useSearchParams } from "next/navigation";
import { ReactNode } from "react";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

// export const metadata: Metadata = {
//   title: "EduAIpro",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const AUTH_PATHS = ["/login", "/register"];
  const LANDING_PATHS = ["/", "/faq", "/courses"];
  const DefaultLayout = ({ children }: { children: ReactNode }) => (
    <main>{children}</main>
  );
  let AppLayout: ({
    children,
  }: {
    children: React.ReactNode;
  }) => React.JSX.Element = Container;
  if (LANDING_PATHS.includes(pathname)) {
    AppLayout = Container;
  }
  if (AUTH_PATHS.includes(pathname)) {
    DefaultLayout.displayName = "LoginLayout";
    AppLayout = DefaultLayout;
  }
  if (pathname.includes("/dashboard")) {
    DefaultLayout.displayName = "DashboardLayout";
    AppLayout = DefaultLayout;
  }
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Theme>
          <AppLayout>{children}</AppLayout>
        </Theme>
      </body>
    </html>
  );
}
