"use client";

import AppLayoutBase from "@/components/layout/app";
import { Toaster } from "@/components/ui/toaster";
import "@radix-ui/themes/styles.css";
import { Montserrat, Work_Sans } from "next/font/google";
import { QueryClient } from "react-query";
import "./globals.css";

const queryClient = new QueryClient();

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

// export const metadata: Metadata = {
//   title: "EduAIpro",
//   description: "Generated by create next app",
// };

// export const metadata: Metadata = {
//   title: "EduAIPro | The world's best AI-Powered Accredited CPD Program",
//   description:
//     "Transform your teaching with EduAIPro's Accredited Continued Professional Development (CPD) courses. Designed for mentors, teaching assistants, primary, secondary, and higher institution educators, our AI-powered platform equips you with the tools to thrive and make a lasting impact.",
//   keywords: [
//     "Professional development",
//     "professional development",
//     "professional development courses",
//     "education",
//     "AI",
//     "Teachers training",
//     "Mentors professional development",
//   ],
//   referrer: "origin-when-cross-origin",
//   colorScheme: "light",
//   creator: "EduAIPro",
//   publisher: "EduAIPro",
//   openGraph: {
//     title: "EduAIPro",
//     description: "The world's best AI-Powered Accredited CPD Program",
//     url: "https://eduaipro.ng",
//     siteName: "EduAIPro",
//     images: [
//       {
//         url: "/og.png",
//         width: 1200,
//         height: 800,
//       },
//     ],
//     locale: "en_US",
//     type: "website",
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${montserrat.variable} ${workSans.variable} antialiased`}
    >
      <body className={montserrat.className}>
        <AppLayoutBase>{children}</AppLayoutBase>
        <Toaster />
      </body>
    </html>
  );
}
