//MUTATIONS

// user
export const SIGNUP_EDUCATOR_MUTATION_KEY = "SIGNUP_EDUCATOR_MUTATION_KEY";
export const LOGIN_MUTATION_KEY = "LOGIN_MUTATION_KEY";
export const UPDATE_PROFILE_MUTATION_KEY = "UPDATE_PROFILE_MUTATION_KEY";
