//MUTATIONS

// user
export const SIGNUP_EDUCATOR_MUTATION_KEY = "SIGNUP_EDUCATOR_MUTATION_KEY";
export const LOGIN_MUTATION_KEY = "LOGIN_MUTATION_KEY";
export const UPDATE_PROFILE_MUTATION_KEY = "UPDATE_PROFILE_MUTATION_KEY";

// SCHOOL QUERIES
export const GET_SCHOOL_BY_ID_QUERY_KEY = "GET_SCHOOL_BY_ID_QUERY_KEY";
export const GET_ALL_SCHOOL_TEACHERS_QUERY_KEY =
  "GET_ALL_SCHOOL_TEACHERS_QUERY_KEY";
