import { Admin } from "./admin";
export const adminData: Admin[] = [
    {
        id: 1,
        name: "Oliver Thompson",
        email: "elmer_boyle1@gmail.com",
        schoolAffiliation: "Riverside Academy",
        position: "Teacher",
        status: "Active",
        dateJoined: "12/03/25",
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Teacher",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 3,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Principal",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 4,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "School Counselor",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 5,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Math Teacher",
        status: "Active",
        dateJoined: "03/15/25",
    },
    {
        id: 6,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "School Counselor",
        status: "Inactive",
        dateJoined: "03/15/25",
    }, {
        id: 7,
        name: "Elmer Boyle",
        email: "elmer_boyle1@gmail.com",
        schoolAffiliation: "Riverside Academy",
        position: "Primary Teacher",
        status: "Active",
        dateJoined: "12/03/25",
    },
    {
        id: 8,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Secondary Teacher",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 9,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Secondary Teacher",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 10,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Secondary Teacher",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 11,
        name: "Jane Smith",
        email: "jane@example.com",
        schoolAffiliation: "Science High School",
        position: "Secondary Teacher",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
    {
        id: 12,
        name: "Jane Smith",
        email: "jane@example.com",

        schoolAffiliation: "Science High School",
        position: "Secondary Teacher",
        status: "Inactive",
        dateJoined: "03/15/25",
    },
];