import { Support } from "./support";
export const supportsData: Support[] = [
  {
    id: 1,
    ticketId: "#TC-193",
    ticketName: "Payment processing error",
    priority: "High",
    requester: "Emily Chen",
    assignee: "Michael Rivera",
    status: "In Progress",
    requestDate: "12/04/25",
  },
  {
    id: 2,
    ticketId: "#TC-194",
    ticketName: "Feature request for notifications",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "Pending",
    requestDate: "10/17/24",
  },
  {
    id: 3,
    ticketId: "#TC-195",
    ticketName: "Bug in mobile app",
    priority: "Low",
    requester: "Bob Williams",
    assignee: "Alice Johnson",
    status: "Pending",
    requestDate: "11/20/24",
  },
  {
    id: 4,
    ticketId: "#TC-196",
    ticketName: "Website loading issues",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "Resolved",
    requestDate: "11/20/24",
  },
  {
    id: 5,
    ticketId: "#TC-197",
    ticketName: "Request for account deletion",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "In Progress",
    requestDate: "11/20/24",
  },
  {
    id: 6,
    ticketId: "#TC-198",
    ticketName: "Duplicate account discovered",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "Resolved",
    requestDate: "11/20/24",
  },
  {
    id: 7,
    ticketId: "#TC-199",
    ticketName: "Feedback on user interface",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "In Progress",
    requestDate: "11/20/24",
  },
  {
    id: 8,
    ticketId: "#TC-200",
    ticketName: "API integration failure",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "Pending",
    requestDate: "11/20/24",
  },
  {
    id: 9,
    ticketId: "#TC-201",
    ticketName: "App crashing on launch",
    priority: "Low",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "Resolved",
    requestDate: "11/20/24",
  },
 {
    id: 10,
    ticketId: "#TC-202",
    ticketName: "User cannot reset password",
    priority: "Medium",
    requester: "Alice Johnson",
    assignee: "David Lee",
    status: "In Progress",
    requestDate: "11/20/24",
  },
 {
    id: 11,
    ticketId: "#TC-203",
    ticketName: "Minor UI glitch in settings",
    priority: "Low",
    requester: "Alice Johnson",
    assignee: "David Lee",
    requestDate: "11/20/24",
    status: "In Progress",
  },
 {
    id: 12,
    ticketId: "#TC-204",
    ticketName: "Request for feature demo",
    priority: "Low",
    requester: "Alice Johnson",
    assignee: "David Lee",
    requestDate: "11/20/24",
    status: "Pending",
  },
];
