import { Survey } from "./survey";
export const surveysData: Survey[] = [
  {
    id: 1,
    name: "How satisfied are you with our courses",
    targetAudience: "Teachers",
    dateCreated: "10/16/24",
    totalResponse: 2_345,
    status: "Active",
  },
  {
    id: 2,
    name: "How satisfied are you with our customer service",
    targetAudience: "Green Vile Academy",
    dateCreated: "10/17/24",
    totalResponse: 1_987,
    status: "Active",
  },
  {
    id: 3,
    name: "How satisfied are you with our website usability",
    targetAudience: "Mentors",
    dateCreated: "10/18/24",
    totalResponse: 2_450,
    status: "Active",
  },
  {
    id: 4,
    name: "How satisfied are you with our billing process",
    targetAudience: "Primary Teachers",
    dateCreated: "10/19/24",
    totalResponse: 1_234,
    status: "Active",
  },
  {
    id: 5,
    name: "How satisfied are you with our product quality",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/20/24",
    totalResponse: 3_001,
    status: "Active",
  },
  {
    id: 6,
    name: "How satisfied are you with our technical support",
    targetAudience: "Teaching Assist",
    dateCreated: "10/21/24",
    totalResponse: 2_876,
    status: "Active",
  },
  {
    id: 7,
    name: "How satisfied are you with our learning materials",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/22/24",
    totalResponse: 1_800,
    status: "Active",
  },
  {
    id: 8,
    name: "How satisfied are you with our communication",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/23/24",
    totalResponse: 2_458,
    status: "Active",
  },
  {
    id: 9,
    name: "How satisfied are you with our event organization",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/24/24",
    totalResponse: 1_475,
    status: "Active",
  },
 {
    id: 10,
    name: "How satisfied are you with our event organization",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/24/24",
    totalResponse: 1_475,
    status: "Active",
  },
 {
    id: 11,
    name: "How satisfied are you with our event organization",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/24/24",
    totalResponse: 1_475,
    status: "Active",
  },
 {
    id: 12,
    name: "How satisfied are you with our event organization",
    targetAudience: "Secondary Teachers",
    dateCreated: "10/24/24",
    totalResponse: 1_475,
    status: "Active",
  },
];
