import { Teacher } from "./Teacher";
export const teachersData: Teacher[] = [
  {
    id: 1,
    name: "Elmer Boyle",
    email: "elmer_boyle1@gmail.com",
    phone: "(706)-615-9242",
    school: "Riverside Academy",
    teachingLevel: "Primary",
    status: "Active",
    dateJoined: "12/03/25",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 3,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 4,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 5,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 6,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  }, {
    id: 7,
    name: "Elmer Boyle",
    email: "elmer_boyle1@gmail.com",
    phone: "(706)-615-9242",
    school: "Riverside Academy",
    teachingLevel: "Primary",
    status: "Active",
    dateJoined: "12/03/25",
  },
  {
    id: 8,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 9,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 10,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 11,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
    {
    id: 12,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    school: "Science High School",
    teachingLevel: "Secondary",
    status: "Inactive",
    dateJoined: "03/15/25",
  },
];